import { danger } from "danger"

export const labels = {
  "Version: Patch": {
    color: "E0E4CC",
    description: "A deploy for bug fixes or minor changes",
  },
  "Version: Minor": {
    color: "A7DBD8",
    description: "A deploy for new features",
  },
  "Version: Major": {
    color: "FA6900",
    description: "A deploy for breaking changes to clients",
  },
  "Version: Trivial": {
    color: "A7DBD8",
    description: "Skip a deploy for this PR",
  },
  Docs: {
    color: "#64EA72",
    description: "Documentation only changes",
  },
}

// Add a version label to PRs that don't already have a version indicator
// https://github.com/artsy/reaction/issues/1095
//
export default async () => {
  const pr = danger.github.pr

  const hasAutoRC = await danger.github.utils.fileContents(".autorc")
  if (!hasAutoRC) {
    console.log(`Skipping, because this repo does not have an .autorc file.`)
    return
  }

  let labelName: keyof typeof labels = "Version: Minor"

  // Someone's already made a decision on the version
  const hasVersionLabel = danger.github.issue.labels.find(label => Object.keys(labels).includes(label.name))
  if (hasVersionLabel) {
    console.log(`Skipping, because this PR already has a version label.`)
    return
  }

  const config = {
    owner: pr.base.user.login,
    repo: pr.base.repo.name,
  }

  const api = danger.github.api
  const existingLabels = await api.issues.listLabelsForRepo(config)
  const versionExists = existingLabels.data.find(label => Object.keys(labels).includes(label.name))

  // Check to see if the label exists for this repo. If not, make the full set
  if (!versionExists) {
    console.log(`Creating labels for release versions, because we're running on a new repo.`)
    for (let [label, labelProperties] of Object.entries(labels)) {
      await api.issues.createLabel({
        name: label,
        ...config,
        ...labelProperties,
      })
    }
  }

  // If it's a Netlify CMS PR, use the docs label
  if (pr.body.includes("Automatically generated by Netlify CMS")) {
    labelName = "Docs"
  }

  // If it's a Dependabot PR, use the trivial version label
  if (danger.github.issue.labels.find(label => label.name === "dependencies")) {
    labelName = "Version: Trivial"
  }

  // Add the label
  console.log(`Adding the \`${labelName}\` label to this PR.`)
  await api.issues.addLabels({
    number: pr.number,
    ...config,
    labels: [labelName],
  })
}
